export default {
  BOT_TOKEN: "YOUR_TOKEN_BOT",
  OWNER_ID: "YOUR_ID",
  OWNER_USERNAME: "YOUR_USERNANE",
  CHANNEL_URL: "https://t.me/CHANNEL",
  PANEL_URL: "YOUR_PANEL_URL",
  APPLICATION_API_KEY: "YOUR_APLICATION_API_KEY",
  DEFAULT_LOCATION_ID: 1,
  DEFAULT_EGG_ID: 17
};
